package com.lanqiao.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.user_id
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.user_email
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.user_phone
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.user_unionid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String userUnionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.openid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.nick_name
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.face_url
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String faceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.channelid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String channelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.create_time
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.user_status
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.userpass
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String userpass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.password_type
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private Integer passwordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.salt
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gl_user.appuuid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private String appuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gl_user
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.user_id
     *
     * @return the value of gl_user.user_id
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.user_id
     *
     * @param userId the value for gl_user.user_id
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.user_email
     *
     * @return the value of gl_user.user_email
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.user_email
     *
     * @param userEmail the value for gl_user.user_email
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.user_phone
     *
     * @return the value of gl_user.user_phone
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.user_phone
     *
     * @param userPhone the value for gl_user.user_phone
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.user_unionid
     *
     * @return the value of gl_user.user_unionid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getUserUnionid() {
        return userUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.user_unionid
     *
     * @param userUnionid the value for gl_user.user_unionid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setUserUnionid(String userUnionid) {
        this.userUnionid = userUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.openid
     *
     * @return the value of gl_user.openid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.openid
     *
     * @param openid the value for gl_user.openid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.nick_name
     *
     * @return the value of gl_user.nick_name
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.nick_name
     *
     * @param nickName the value for gl_user.nick_name
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.face_url
     *
     * @return the value of gl_user.face_url
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getFaceUrl() {
        return faceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.face_url
     *
     * @param faceUrl the value for gl_user.face_url
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setFaceUrl(String faceUrl) {
        this.faceUrl = faceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.channelid
     *
     * @return the value of gl_user.channelid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.channelid
     *
     * @param channelid the value for gl_user.channelid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.create_time
     *
     * @return the value of gl_user.create_time
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.create_time
     *
     * @param createTime the value for gl_user.create_time
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.user_status
     *
     * @return the value of gl_user.user_status
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.user_status
     *
     * @param userStatus the value for gl_user.user_status
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.userpass
     *
     * @return the value of gl_user.userpass
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getUserpass() {
        return userpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.userpass
     *
     * @param userpass the value for gl_user.userpass
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setUserpass(String userpass) {
        this.userpass = userpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.password_type
     *
     * @return the value of gl_user.password_type
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public Integer getPasswordType() {
        return passwordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.password_type
     *
     * @param passwordType the value for gl_user.password_type
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setPasswordType(Integer passwordType) {
        this.passwordType = passwordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.salt
     *
     * @return the value of gl_user.salt
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.salt
     *
     * @param salt the value for gl_user.salt
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gl_user.appuuid
     *
     * @return the value of gl_user.appuuid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public String getAppuuid() {
        return appuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gl_user.appuuid
     *
     * @param appuuid the value for gl_user.appuuid
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    public void setAppuuid(String appuuid) {
        this.appuuid = appuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gl_user
     *
     * @mbg.generated Sat Feb 22 09:01:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userUnionid=").append(userUnionid);
        sb.append(", openid=").append(openid);
        sb.append(", nickName=").append(nickName);
        sb.append(", faceUrl=").append(faceUrl);
        sb.append(", channelid=").append(channelid);
        sb.append(", createTime=").append(createTime);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", userpass=").append(userpass);
        sb.append(", passwordType=").append(passwordType);
        sb.append(", salt=").append(salt);
        sb.append(", appuuid=").append(appuuid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}