package com.lanqiao.model.exam;

import java.io.Serializable;

public class EXCompanyRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_company_role.role_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_company_role.role_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_company_role.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_company_role.role_desc
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_company_role
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_company_role.role_id
     *
     * @return the value of ex_company_role.role_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_company_role.role_id
     *
     * @param roleId the value for ex_company_role.role_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_company_role.role_name
     *
     * @return the value of ex_company_role.role_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_company_role.role_name
     *
     * @param roleName the value for ex_company_role.role_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_company_role.comp_id
     *
     * @return the value of ex_company_role.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_company_role.comp_id
     *
     * @param compId the value for ex_company_role.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_company_role.role_desc
     *
     * @return the value of ex_company_role.role_desc
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_company_role.role_desc
     *
     * @param roleDesc the value for ex_company_role.role_desc
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_company_role
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", roleName=").append(roleName);
        sb.append(", compId=").append(compId);
        sb.append(", roleDesc=").append(roleDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}