package com.lanqiao.model.exam;

import java.io.Serializable;

public class EXExamStudent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_exam_student.stu_userid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long stuUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_exam_student.exam_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_exam_student.stu_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_exam_student.stu_phone
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private String stuPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_exam_student.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_exam_student.stu_extdata_json
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private String stuExtdataJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_exam_student
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_exam_student.stu_userid
     *
     * @return the value of ex_exam_student.stu_userid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getStuUserid() {
        return stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_exam_student.stu_userid
     *
     * @param stuUserid the value for ex_exam_student.stu_userid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setStuUserid(Long stuUserid) {
        this.stuUserid = stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_exam_student.exam_id
     *
     * @return the value of ex_exam_student.exam_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_exam_student.exam_id
     *
     * @param examId the value for ex_exam_student.exam_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setExamId(Long examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_exam_student.stu_name
     *
     * @return the value of ex_exam_student.stu_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_exam_student.stu_name
     *
     * @param stuName the value for ex_exam_student.stu_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_exam_student.stu_phone
     *
     * @return the value of ex_exam_student.stu_phone
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_exam_student.stu_phone
     *
     * @param stuPhone the value for ex_exam_student.stu_phone
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_exam_student.comp_id
     *
     * @return the value of ex_exam_student.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_exam_student.comp_id
     *
     * @param compId the value for ex_exam_student.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_exam_student.stu_extdata_json
     *
     * @return the value of ex_exam_student.stu_extdata_json
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public String getStuExtdataJson() {
        return stuExtdataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_exam_student.stu_extdata_json
     *
     * @param stuExtdataJson the value for ex_exam_student.stu_extdata_json
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setStuExtdataJson(String stuExtdataJson) {
        this.stuExtdataJson = stuExtdataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_exam_student
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stuUserid=").append(stuUserid);
        sb.append(", examId=").append(examId);
        sb.append(", stuName=").append(stuName);
        sb.append(", stuPhone=").append(stuPhone);
        sb.append(", compId=").append(compId);
        sb.append(", stuExtdataJson=").append(stuExtdataJson);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}