package com.lanqiao.model.exam;

import java.io.Serializable;
import java.util.Date;

public class EXPaperInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.paperid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long paperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.paper_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private String paperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.easyid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Integer easyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Integer catalogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.create_time
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.cm_userid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long cmUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.owner_type
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Integer ownerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_info.totalscore
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Float totalscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_paper_info
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.paperid
     *
     * @return the value of ex_paper_info.paperid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.paperid
     *
     * @param paperid the value for ex_paper_info.paperid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setPaperid(Long paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.paper_name
     *
     * @return the value of ex_paper_info.paper_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.paper_name
     *
     * @param paperName the value for ex_paper_info.paper_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.easyid
     *
     * @return the value of ex_paper_info.easyid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Integer getEasyid() {
        return easyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.easyid
     *
     * @param easyid the value for ex_paper_info.easyid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setEasyid(Integer easyid) {
        this.easyid = easyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.catalogid
     *
     * @return the value of ex_paper_info.catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Integer getCatalogid() {
        return catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.catalogid
     *
     * @param catalogid the value for ex_paper_info.catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCatalogid(Integer catalogid) {
        this.catalogid = catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.create_time
     *
     * @return the value of ex_paper_info.create_time
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.create_time
     *
     * @param createTime the value for ex_paper_info.create_time
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.cm_userid
     *
     * @return the value of ex_paper_info.cm_userid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.cm_userid
     *
     * @param cmUserid the value for ex_paper_info.cm_userid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCmUserid(Long cmUserid) {
        this.cmUserid = cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.comp_id
     *
     * @return the value of ex_paper_info.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.comp_id
     *
     * @param compId the value for ex_paper_info.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.owner_type
     *
     * @return the value of ex_paper_info.owner_type
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Integer getOwnerType() {
        return ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.owner_type
     *
     * @param ownerType the value for ex_paper_info.owner_type
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setOwnerType(Integer ownerType) {
        this.ownerType = ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_info.totalscore
     *
     * @return the value of ex_paper_info.totalscore
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Float getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_info.totalscore
     *
     * @param totalscore the value for ex_paper_info.totalscore
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setTotalscore(Float totalscore) {
        this.totalscore = totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_paper_info
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", paperid=").append(paperid);
        sb.append(", paperName=").append(paperName);
        sb.append(", easyid=").append(easyid);
        sb.append(", catalogid=").append(catalogid);
        sb.append(", createTime=").append(createTime);
        sb.append(", cmUserid=").append(cmUserid);
        sb.append(", compId=").append(compId);
        sb.append(", ownerType=").append(ownerType);
        sb.append(", totalscore=").append(totalscore);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}