package com.lanqiao.model.exam;

import java.io.Serializable;

public class EXPaperQuestionsWithBLOBs extends EXPaperQuestions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_questions.q_detail
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    private String qDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_questions.q_title
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    private String qTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_paper_questions.q_analysis
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    private String qAnalysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_paper_questions
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_questions.q_detail
     *
     * @return the value of ex_paper_questions.q_detail
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    public String getqDetail() {
        return qDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_questions.q_detail
     *
     * @param qDetail the value for ex_paper_questions.q_detail
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    public void setqDetail(String qDetail) {
        this.qDetail = qDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_questions.q_title
     *
     * @return the value of ex_paper_questions.q_title
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    public String getqTitle() {
        return qTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_questions.q_title
     *
     * @param qTitle the value for ex_paper_questions.q_title
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    public void setqTitle(String qTitle) {
        this.qTitle = qTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_paper_questions.q_analysis
     *
     * @return the value of ex_paper_questions.q_analysis
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    public String getqAnalysis() {
        return qAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_paper_questions.q_analysis
     *
     * @param qAnalysis the value for ex_paper_questions.q_analysis
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    public void setqAnalysis(String qAnalysis) {
        this.qAnalysis = qAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_paper_questions
     *
     * @mbg.generated Wed Oct 09 14:09:08 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qDetail=").append(qDetail);
        sb.append(", qTitle=").append(qTitle);
        sb.append(", qAnalysis=").append(qAnalysis);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}