package com.lanqiao.model.exam;

import java.io.Serializable;

public class EXQuestionCatalog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_question_catalog.catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Integer catalogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_question_catalog.catalog_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private String catalogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_question_catalog.pid_catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Integer pidCatalogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_question_catalog.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_question_catalog
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_question_catalog.catalogid
     *
     * @return the value of ex_question_catalog.catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Integer getCatalogid() {
        return catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_question_catalog.catalogid
     *
     * @param catalogid the value for ex_question_catalog.catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCatalogid(Integer catalogid) {
        this.catalogid = catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_question_catalog.catalog_name
     *
     * @return the value of ex_question_catalog.catalog_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_question_catalog.catalog_name
     *
     * @param catalogName the value for ex_question_catalog.catalog_name
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_question_catalog.pid_catalogid
     *
     * @return the value of ex_question_catalog.pid_catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Integer getPidCatalogid() {
        return pidCatalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_question_catalog.pid_catalogid
     *
     * @param pidCatalogid the value for ex_question_catalog.pid_catalogid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setPidCatalogid(Integer pidCatalogid) {
        this.pidCatalogid = pidCatalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_question_catalog.comp_id
     *
     * @return the value of ex_question_catalog.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_question_catalog.comp_id
     *
     * @param compId the value for ex_question_catalog.comp_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_question_catalog
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", catalogid=").append(catalogid);
        sb.append(", catalogName=").append(catalogName);
        sb.append(", pidCatalogid=").append(pidCatalogid);
        sb.append(", compId=").append(compId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}