package com.lanqiao.model.exam;

import java.io.Serializable;

public class EXQuestionType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_question_type.q_typeid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Integer qTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_question_type.ques_typename
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private String quesTypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_question_type
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_question_type.q_typeid
     *
     * @return the value of ex_question_type.q_typeid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Integer getqTypeid() {
        return qTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_question_type.q_typeid
     *
     * @param qTypeid the value for ex_question_type.q_typeid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setqTypeid(Integer qTypeid) {
        this.qTypeid = qTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_question_type.ques_typename
     *
     * @return the value of ex_question_type.ques_typename
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public String getQuesTypename() {
        return quesTypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_question_type.ques_typename
     *
     * @param quesTypename the value for ex_question_type.ques_typename
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setQuesTypename(String quesTypename) {
        this.quesTypename = quesTypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_question_type
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qTypeid=").append(qTypeid);
        sb.append(", quesTypename=").append(quesTypename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}