package com.lanqiao.model.exam;

import java.io.Serializable;

public class EXRoleWithmodule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_role_withmodule.nnid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long nnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_role_withmodule.role_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_role_withmodule.moduleid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private Integer moduleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_role_withmodule
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_role_withmodule.nnid
     *
     * @return the value of ex_role_withmodule.nnid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getNnid() {
        return nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_role_withmodule.nnid
     *
     * @param nnid the value for ex_role_withmodule.nnid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setNnid(Long nnid) {
        this.nnid = nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_role_withmodule.role_id
     *
     * @return the value of ex_role_withmodule.role_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_role_withmodule.role_id
     *
     * @param roleId the value for ex_role_withmodule.role_id
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_role_withmodule.moduleid
     *
     * @return the value of ex_role_withmodule.moduleid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_role_withmodule.moduleid
     *
     * @param moduleid the value for ex_role_withmodule.moduleid
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_role_withmodule
     *
     * @mbggenerated Tue Dec 24 15:00:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nnid=").append(nnid);
        sb.append(", roleId=").append(roleId);
        sb.append(", moduleid=").append(moduleid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}