package com.lanqiao.model.exam;

import java.io.Serializable;
import java.util.Date;

public class EXStudentExaminfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stuexamid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Long stuexamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.exam_id
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Long examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.paperid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Long paperid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.exam_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String examName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.passscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Float passscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.totalscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Float totalscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.showscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer showscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.create_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.papertime_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer papertimeMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.begin_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.end_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.time_minute
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer timeMinute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.ranktitle_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer ranktitleMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.rankoption_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer rankoptionMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.login_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer loginMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.explain_answer
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer explainAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.comp_id
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.cm_userid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Long cmUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.score_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer scoreMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.paper_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String paperName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.easyid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer easyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.catalogid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer catalogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.exam_type
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer examType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_userid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Long stuUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_phone
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String stuPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_submit_status
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer stuSubmitStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_score
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Float stuScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_begin_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Date stuBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_end_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Date stuEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_judge_status
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer stuJudgeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_ssouserid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Long stuSsouserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_submit_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Date stuSubmitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.question_count
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer questionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.program_language
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String programLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.camera_path
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String cameraPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.ifcheat
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private Integer ifcheat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.cheatreason
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String cheatreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_student_examinfo
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stuexamid
     *
     * @return the value of ex_student_examinfo.stuexamid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Long getStuexamid() {
        return stuexamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stuexamid
     *
     * @param stuexamid the value for ex_student_examinfo.stuexamid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuexamid(Long stuexamid) {
        this.stuexamid = stuexamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.exam_id
     *
     * @return the value of ex_student_examinfo.exam_id
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Long getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.exam_id
     *
     * @param examId the value for ex_student_examinfo.exam_id
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setExamId(Long examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.paperid
     *
     * @return the value of ex_student_examinfo.paperid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Long getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.paperid
     *
     * @param paperid the value for ex_student_examinfo.paperid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setPaperid(Long paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.exam_name
     *
     * @return the value of ex_student_examinfo.exam_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.exam_name
     *
     * @param examName the value for ex_student_examinfo.exam_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setExamName(String examName) {
        this.examName = examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.passscore
     *
     * @return the value of ex_student_examinfo.passscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Float getPassscore() {
        return passscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.passscore
     *
     * @param passscore the value for ex_student_examinfo.passscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setPassscore(Float passscore) {
        this.passscore = passscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.totalscore
     *
     * @return the value of ex_student_examinfo.totalscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Float getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.totalscore
     *
     * @param totalscore the value for ex_student_examinfo.totalscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setTotalscore(Float totalscore) {
        this.totalscore = totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.showscore
     *
     * @return the value of ex_student_examinfo.showscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getShowscore() {
        return showscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.showscore
     *
     * @param showscore the value for ex_student_examinfo.showscore
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setShowscore(Integer showscore) {
        this.showscore = showscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.create_time
     *
     * @return the value of ex_student_examinfo.create_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.create_time
     *
     * @param createTime the value for ex_student_examinfo.create_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.papertime_mode
     *
     * @return the value of ex_student_examinfo.papertime_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getPapertimeMode() {
        return papertimeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.papertime_mode
     *
     * @param papertimeMode the value for ex_student_examinfo.papertime_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setPapertimeMode(Integer papertimeMode) {
        this.papertimeMode = papertimeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.begin_time
     *
     * @return the value of ex_student_examinfo.begin_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.begin_time
     *
     * @param beginTime the value for ex_student_examinfo.begin_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.end_time
     *
     * @return the value of ex_student_examinfo.end_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.end_time
     *
     * @param endTime the value for ex_student_examinfo.end_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.time_minute
     *
     * @return the value of ex_student_examinfo.time_minute
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getTimeMinute() {
        return timeMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.time_minute
     *
     * @param timeMinute the value for ex_student_examinfo.time_minute
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setTimeMinute(Integer timeMinute) {
        this.timeMinute = timeMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.ranktitle_mode
     *
     * @return the value of ex_student_examinfo.ranktitle_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getRanktitleMode() {
        return ranktitleMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.ranktitle_mode
     *
     * @param ranktitleMode the value for ex_student_examinfo.ranktitle_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setRanktitleMode(Integer ranktitleMode) {
        this.ranktitleMode = ranktitleMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.rankoption_mode
     *
     * @return the value of ex_student_examinfo.rankoption_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getRankoptionMode() {
        return rankoptionMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.rankoption_mode
     *
     * @param rankoptionMode the value for ex_student_examinfo.rankoption_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setRankoptionMode(Integer rankoptionMode) {
        this.rankoptionMode = rankoptionMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.login_mode
     *
     * @return the value of ex_student_examinfo.login_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getLoginMode() {
        return loginMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.login_mode
     *
     * @param loginMode the value for ex_student_examinfo.login_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setLoginMode(Integer loginMode) {
        this.loginMode = loginMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.explain_answer
     *
     * @return the value of ex_student_examinfo.explain_answer
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getExplainAnswer() {
        return explainAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.explain_answer
     *
     * @param explainAnswer the value for ex_student_examinfo.explain_answer
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setExplainAnswer(Integer explainAnswer) {
        this.explainAnswer = explainAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.comp_id
     *
     * @return the value of ex_student_examinfo.comp_id
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.comp_id
     *
     * @param compId the value for ex_student_examinfo.comp_id
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.cm_userid
     *
     * @return the value of ex_student_examinfo.cm_userid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Long getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.cm_userid
     *
     * @param cmUserid the value for ex_student_examinfo.cm_userid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setCmUserid(Long cmUserid) {
        this.cmUserid = cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.score_mode
     *
     * @return the value of ex_student_examinfo.score_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getScoreMode() {
        return scoreMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.score_mode
     *
     * @param scoreMode the value for ex_student_examinfo.score_mode
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setScoreMode(Integer scoreMode) {
        this.scoreMode = scoreMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.paper_name
     *
     * @return the value of ex_student_examinfo.paper_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.paper_name
     *
     * @param paperName the value for ex_student_examinfo.paper_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.easyid
     *
     * @return the value of ex_student_examinfo.easyid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getEasyid() {
        return easyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.easyid
     *
     * @param easyid the value for ex_student_examinfo.easyid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setEasyid(Integer easyid) {
        this.easyid = easyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.catalogid
     *
     * @return the value of ex_student_examinfo.catalogid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getCatalogid() {
        return catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.catalogid
     *
     * @param catalogid the value for ex_student_examinfo.catalogid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setCatalogid(Integer catalogid) {
        this.catalogid = catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.exam_type
     *
     * @return the value of ex_student_examinfo.exam_type
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getExamType() {
        return examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.exam_type
     *
     * @param examType the value for ex_student_examinfo.exam_type
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setExamType(Integer examType) {
        this.examType = examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_userid
     *
     * @return the value of ex_student_examinfo.stu_userid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Long getStuUserid() {
        return stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_userid
     *
     * @param stuUserid the value for ex_student_examinfo.stu_userid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuUserid(Long stuUserid) {
        this.stuUserid = stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_name
     *
     * @return the value of ex_student_examinfo.stu_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_name
     *
     * @param stuName the value for ex_student_examinfo.stu_name
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_phone
     *
     * @return the value of ex_student_examinfo.stu_phone
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_phone
     *
     * @param stuPhone the value for ex_student_examinfo.stu_phone
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_submit_status
     *
     * @return the value of ex_student_examinfo.stu_submit_status
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getStuSubmitStatus() {
        return stuSubmitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_submit_status
     *
     * @param stuSubmitStatus the value for ex_student_examinfo.stu_submit_status
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuSubmitStatus(Integer stuSubmitStatus) {
        this.stuSubmitStatus = stuSubmitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_score
     *
     * @return the value of ex_student_examinfo.stu_score
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Float getStuScore() {
        return stuScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_score
     *
     * @param stuScore the value for ex_student_examinfo.stu_score
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuScore(Float stuScore) {
        this.stuScore = stuScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_begin_time
     *
     * @return the value of ex_student_examinfo.stu_begin_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Date getStuBeginTime() {
        return stuBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_begin_time
     *
     * @param stuBeginTime the value for ex_student_examinfo.stu_begin_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuBeginTime(Date stuBeginTime) {
        this.stuBeginTime = stuBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_end_time
     *
     * @return the value of ex_student_examinfo.stu_end_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Date getStuEndTime() {
        return stuEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_end_time
     *
     * @param stuEndTime the value for ex_student_examinfo.stu_end_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuEndTime(Date stuEndTime) {
        this.stuEndTime = stuEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_judge_status
     *
     * @return the value of ex_student_examinfo.stu_judge_status
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getStuJudgeStatus() {
        return stuJudgeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_judge_status
     *
     * @param stuJudgeStatus the value for ex_student_examinfo.stu_judge_status
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuJudgeStatus(Integer stuJudgeStatus) {
        this.stuJudgeStatus = stuJudgeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_ssouserid
     *
     * @return the value of ex_student_examinfo.stu_ssouserid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Long getStuSsouserid() {
        return stuSsouserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_ssouserid
     *
     * @param stuSsouserid the value for ex_student_examinfo.stu_ssouserid
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuSsouserid(Long stuSsouserid) {
        this.stuSsouserid = stuSsouserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_submit_time
     *
     * @return the value of ex_student_examinfo.stu_submit_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Date getStuSubmitTime() {
        return stuSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_submit_time
     *
     * @param stuSubmitTime the value for ex_student_examinfo.stu_submit_time
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuSubmitTime(Date stuSubmitTime) {
        this.stuSubmitTime = stuSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.question_count
     *
     * @return the value of ex_student_examinfo.question_count
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getQuestionCount() {
        return questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.question_count
     *
     * @param questionCount the value for ex_student_examinfo.question_count
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setQuestionCount(Integer questionCount) {
        this.questionCount = questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.program_language
     *
     * @return the value of ex_student_examinfo.program_language
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getProgramLanguage() {
        return programLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.program_language
     *
     * @param programLanguage the value for ex_student_examinfo.program_language
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setProgramLanguage(String programLanguage) {
        this.programLanguage = programLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.camera_path
     *
     * @return the value of ex_student_examinfo.camera_path
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getCameraPath() {
        return cameraPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.camera_path
     *
     * @param cameraPath the value for ex_student_examinfo.camera_path
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setCameraPath(String cameraPath) {
        this.cameraPath = cameraPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.ifcheat
     *
     * @return the value of ex_student_examinfo.ifcheat
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public Integer getIfcheat() {
        return ifcheat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.ifcheat
     *
     * @param ifcheat the value for ex_student_examinfo.ifcheat
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setIfcheat(Integer ifcheat) {
        this.ifcheat = ifcheat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.cheatreason
     *
     * @return the value of ex_student_examinfo.cheatreason
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getCheatreason() {
        return cheatreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.cheatreason
     *
     * @param cheatreason the value for ex_student_examinfo.cheatreason
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setCheatreason(String cheatreason) {
        this.cheatreason = cheatreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_student_examinfo
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stuexamid=").append(stuexamid);
        sb.append(", examId=").append(examId);
        sb.append(", paperid=").append(paperid);
        sb.append(", examName=").append(examName);
        sb.append(", passscore=").append(passscore);
        sb.append(", totalscore=").append(totalscore);
        sb.append(", showscore=").append(showscore);
        sb.append(", createTime=").append(createTime);
        sb.append(", papertimeMode=").append(papertimeMode);
        sb.append(", beginTime=").append(beginTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", timeMinute=").append(timeMinute);
        sb.append(", ranktitleMode=").append(ranktitleMode);
        sb.append(", rankoptionMode=").append(rankoptionMode);
        sb.append(", loginMode=").append(loginMode);
        sb.append(", explainAnswer=").append(explainAnswer);
        sb.append(", compId=").append(compId);
        sb.append(", cmUserid=").append(cmUserid);
        sb.append(", scoreMode=").append(scoreMode);
        sb.append(", paperName=").append(paperName);
        sb.append(", easyid=").append(easyid);
        sb.append(", catalogid=").append(catalogid);
        sb.append(", examType=").append(examType);
        sb.append(", stuUserid=").append(stuUserid);
        sb.append(", stuName=").append(stuName);
        sb.append(", stuPhone=").append(stuPhone);
        sb.append(", stuSubmitStatus=").append(stuSubmitStatus);
        sb.append(", stuScore=").append(stuScore);
        sb.append(", stuBeginTime=").append(stuBeginTime);
        sb.append(", stuEndTime=").append(stuEndTime);
        sb.append(", stuJudgeStatus=").append(stuJudgeStatus);
        sb.append(", stuSsouserid=").append(stuSsouserid);
        sb.append(", stuSubmitTime=").append(stuSubmitTime);
        sb.append(", questionCount=").append(questionCount);
        sb.append(", programLanguage=").append(programLanguage);
        sb.append(", cameraPath=").append(cameraPath);
        sb.append(", ifcheat=").append(ifcheat);
        sb.append(", cheatreason=").append(cheatreason);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}