package com.lanqiao.model.exam;

import java.io.Serializable;

public class EXStudentExaminfoWithBLOBs extends EXStudentExaminfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.login_data_json
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String loginDataJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ex_student_examinfo.stu_extdata_json
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private String stuExtdataJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ex_student_examinfo
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.login_data_json
     *
     * @return the value of ex_student_examinfo.login_data_json
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getLoginDataJson() {
        return loginDataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.login_data_json
     *
     * @param loginDataJson the value for ex_student_examinfo.login_data_json
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setLoginDataJson(String loginDataJson) {
        this.loginDataJson = loginDataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ex_student_examinfo.stu_extdata_json
     *
     * @return the value of ex_student_examinfo.stu_extdata_json
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public String getStuExtdataJson() {
        return stuExtdataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ex_student_examinfo.stu_extdata_json
     *
     * @param stuExtdataJson the value for ex_student_examinfo.stu_extdata_json
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    public void setStuExtdataJson(String stuExtdataJson) {
        this.stuExtdataJson = stuExtdataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ex_student_examinfo
     *
     * @mbg.generated Tue Jun 02 11:26:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", loginDataJson=").append(loginDataJson);
        sb.append(", stuExtdataJson=").append(stuExtdataJson);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}