package com.lanqiao.model.order;

import java.io.Serializable;
import java.util.Date;

public class OdDictInvoiceExportConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.dict_id
     *
     * @mbg.generated
     */
    private Integer dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.invoice_export_id
     *
     * @mbg.generated
     */
    private Integer invoiceExportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.invoice_config_id
     *
     * @mbg.generated
     */
    private Integer invoiceConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.tax_flag
     *
     * @mbg.generated
     */
    private String taxFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.tax_rate
     *
     * @mbg.generated
     */
    private String taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.invoice_nature
     *
     * @mbg.generated
     */
    private String invoiceNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.preferential_policy
     *
     * @mbg.generated
     */
    private String preferentialPolicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.goods_code
     *
     * @mbg.generated
     */
    private String goodsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.self_code
     *
     * @mbg.generated
     */
    private String selfCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.zero_code
     *
     * @mbg.generated
     */
    private String zeroCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.vat_management
     *
     * @mbg.generated
     */
    private String vatManagement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_dict_invoice_export_config.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table od_dict_invoice_export_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.dict_id
     *
     * @return the value of od_dict_invoice_export_config.dict_id
     *
     * @mbg.generated
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.dict_id
     *
     * @param dictId the value for od_dict_invoice_export_config.dict_id
     *
     * @mbg.generated
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.invoice_export_id
     *
     * @return the value of od_dict_invoice_export_config.invoice_export_id
     *
     * @mbg.generated
     */
    public Integer getInvoiceExportId() {
        return invoiceExportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.invoice_export_id
     *
     * @param invoiceExportId the value for od_dict_invoice_export_config.invoice_export_id
     *
     * @mbg.generated
     */
    public void setInvoiceExportId(Integer invoiceExportId) {
        this.invoiceExportId = invoiceExportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.project_id
     *
     * @return the value of od_dict_invoice_export_config.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.project_id
     *
     * @param projectId the value for od_dict_invoice_export_config.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.invoice_config_id
     *
     * @return the value of od_dict_invoice_export_config.invoice_config_id
     *
     * @mbg.generated
     */
    public Integer getInvoiceConfigId() {
        return invoiceConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.invoice_config_id
     *
     * @param invoiceConfigId the value for od_dict_invoice_export_config.invoice_config_id
     *
     * @mbg.generated
     */
    public void setInvoiceConfigId(Integer invoiceConfigId) {
        this.invoiceConfigId = invoiceConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.tax_flag
     *
     * @return the value of od_dict_invoice_export_config.tax_flag
     *
     * @mbg.generated
     */
    public String getTaxFlag() {
        return taxFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.tax_flag
     *
     * @param taxFlag the value for od_dict_invoice_export_config.tax_flag
     *
     * @mbg.generated
     */
    public void setTaxFlag(String taxFlag) {
        this.taxFlag = taxFlag == null ? null : taxFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.tax_rate
     *
     * @return the value of od_dict_invoice_export_config.tax_rate
     *
     * @mbg.generated
     */
    public String getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.tax_rate
     *
     * @param taxRate the value for od_dict_invoice_export_config.tax_rate
     *
     * @mbg.generated
     */
    public void setTaxRate(String taxRate) {
        this.taxRate = taxRate == null ? null : taxRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.invoice_nature
     *
     * @return the value of od_dict_invoice_export_config.invoice_nature
     *
     * @mbg.generated
     */
    public String getInvoiceNature() {
        return invoiceNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.invoice_nature
     *
     * @param invoiceNature the value for od_dict_invoice_export_config.invoice_nature
     *
     * @mbg.generated
     */
    public void setInvoiceNature(String invoiceNature) {
        this.invoiceNature = invoiceNature == null ? null : invoiceNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.preferential_policy
     *
     * @return the value of od_dict_invoice_export_config.preferential_policy
     *
     * @mbg.generated
     */
    public String getPreferentialPolicy() {
        return preferentialPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.preferential_policy
     *
     * @param preferentialPolicy the value for od_dict_invoice_export_config.preferential_policy
     *
     * @mbg.generated
     */
    public void setPreferentialPolicy(String preferentialPolicy) {
        this.preferentialPolicy = preferentialPolicy == null ? null : preferentialPolicy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.goods_code
     *
     * @return the value of od_dict_invoice_export_config.goods_code
     *
     * @mbg.generated
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.goods_code
     *
     * @param goodsCode the value for od_dict_invoice_export_config.goods_code
     *
     * @mbg.generated
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode == null ? null : goodsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.self_code
     *
     * @return the value of od_dict_invoice_export_config.self_code
     *
     * @mbg.generated
     */
    public String getSelfCode() {
        return selfCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.self_code
     *
     * @param selfCode the value for od_dict_invoice_export_config.self_code
     *
     * @mbg.generated
     */
    public void setSelfCode(String selfCode) {
        this.selfCode = selfCode == null ? null : selfCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.zero_code
     *
     * @return the value of od_dict_invoice_export_config.zero_code
     *
     * @mbg.generated
     */
    public String getZeroCode() {
        return zeroCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.zero_code
     *
     * @param zeroCode the value for od_dict_invoice_export_config.zero_code
     *
     * @mbg.generated
     */
    public void setZeroCode(String zeroCode) {
        this.zeroCode = zeroCode == null ? null : zeroCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.vat_management
     *
     * @return the value of od_dict_invoice_export_config.vat_management
     *
     * @mbg.generated
     */
    public String getVatManagement() {
        return vatManagement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.vat_management
     *
     * @param vatManagement the value for od_dict_invoice_export_config.vat_management
     *
     * @mbg.generated
     */
    public void setVatManagement(String vatManagement) {
        this.vatManagement = vatManagement == null ? null : vatManagement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.remark
     *
     * @return the value of od_dict_invoice_export_config.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.remark
     *
     * @param remark the value for od_dict_invoice_export_config.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_dict_invoice_export_config.created
     *
     * @return the value of od_dict_invoice_export_config.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_dict_invoice_export_config.created
     *
     * @param created the value for od_dict_invoice_export_config.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}