package com.lanqiao.model.order;

import java.io.Serializable;

public class OdOrderWithBLOBs extends OdOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order.order_reduce_detail_json
     *
     * @mbg.generated
     */
    private String orderReduceDetailJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order.order_group_detail_json
     *
     * @mbg.generated
     */
    private String orderGroupDetailJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order.order_detail_json
     *
     * @mbg.generated
     */
    private String orderDetailJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table od_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order.order_reduce_detail_json
     *
     * @return the value of od_order.order_reduce_detail_json
     *
     * @mbg.generated
     */
    public String getOrderReduceDetailJson() {
        return orderReduceDetailJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order.order_reduce_detail_json
     *
     * @param orderReduceDetailJson the value for od_order.order_reduce_detail_json
     *
     * @mbg.generated
     */
    public void setOrderReduceDetailJson(String orderReduceDetailJson) {
        this.orderReduceDetailJson = orderReduceDetailJson == null ? null : orderReduceDetailJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order.order_group_detail_json
     *
     * @return the value of od_order.order_group_detail_json
     *
     * @mbg.generated
     */
    public String getOrderGroupDetailJson() {
        return orderGroupDetailJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order.order_group_detail_json
     *
     * @param orderGroupDetailJson the value for od_order.order_group_detail_json
     *
     * @mbg.generated
     */
    public void setOrderGroupDetailJson(String orderGroupDetailJson) {
        this.orderGroupDetailJson = orderGroupDetailJson == null ? null : orderGroupDetailJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order.order_detail_json
     *
     * @return the value of od_order.order_detail_json
     *
     * @mbg.generated
     */
    public String getOrderDetailJson() {
        return orderDetailJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order.order_detail_json
     *
     * @param orderDetailJson the value for od_order.order_detail_json
     *
     * @mbg.generated
     */
    public void setOrderDetailJson(String orderDetailJson) {
        this.orderDetailJson = orderDetailJson == null ? null : orderDetailJson.trim();
    }
}