package com.lanqiao.model.order;

import java.io.Serializable;

public class OdOrderRefundWithBLOBs extends OdOrderRefund implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_reason
     *
     * @mbg.generated
     */
    private String refundReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_change_log
     *
     * @mbg.generated
     */
    private String refundChangeLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_detail_json
     *
     * @mbg.generated
     */
    private String refundDetailJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table od_order_refund
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_reason
     *
     * @return the value of od_order_refund.refund_reason
     *
     * @mbg.generated
     */
    public String getRefundReason() {
        return refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_reason
     *
     * @param refundReason the value for od_order_refund.refund_reason
     *
     * @mbg.generated
     */
    public void setRefundReason(String refundReason) {
        this.refundReason = refundReason == null ? null : refundReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_change_log
     *
     * @return the value of od_order_refund.refund_change_log
     *
     * @mbg.generated
     */
    public String getRefundChangeLog() {
        return refundChangeLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_change_log
     *
     * @param refundChangeLog the value for od_order_refund.refund_change_log
     *
     * @mbg.generated
     */
    public void setRefundChangeLog(String refundChangeLog) {
        this.refundChangeLog = refundChangeLog == null ? null : refundChangeLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_detail_json
     *
     * @return the value of od_order_refund.refund_detail_json
     *
     * @mbg.generated
     */
    public String getRefundDetailJson() {
        return refundDetailJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_detail_json
     *
     * @param refundDetailJson the value for od_order_refund.refund_detail_json
     *
     * @mbg.generated
     */
    public void setRefundDetailJson(String refundDetailJson) {
        this.refundDetailJson = refundDetailJson == null ? null : refundDetailJson.trim();
    }
}