package com.lanqiao.model.order;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OdOrderRefund implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_id
     *
     * @mbg.generated
     */
    private Long refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.platform_id
     *
     * @mbg.generated
     */
    private Integer platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_total_amount
     *
     * @mbg.generated
     */
    private BigDecimal refundTotalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_amount_type
     *
     * @mbg.generated
     */
    private Integer refundAmountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_status_id
     *
     * @mbg.generated
     */
    private Integer refundStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_handle_admin_id
     *
     * @mbg.generated
     */
    private Long refundHandleAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_handle_admin_name
     *
     * @mbg.generated
     */
    private String refundHandleAdminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_handle_time
     *
     * @mbg.generated
     */
    private Date refundHandleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_handle_content
     *
     * @mbg.generated
     */
    private String refundHandleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_operator
     *
     * @mbg.generated
     */
    private Long refundOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_operator_name
     *
     * @mbg.generated
     */
    private String refundOperatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_finish_time
     *
     * @mbg.generated
     */
    private Date refundFinishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_close_time
     *
     * @mbg.generated
     */
    private Date refundCloseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.invoice_is_return
     *
     * @mbg.generated
     */
    private Boolean invoiceIsReturn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.express_number
     *
     * @mbg.generated
     */
    private String expressNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.express_status
     *
     * @mbg.generated
     */
    private Boolean expressStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_date
     *
     * @mbg.generated
     */
    private Date refundDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.refund_batch_no
     *
     * @mbg.generated
     */
    private String refundBatchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.creator_type
     *
     * @mbg.generated
     */
    private Integer creatorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.creator
     *
     * @mbg.generated
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_refund.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table od_order_refund
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_id
     *
     * @return the value of od_order_refund.refund_id
     *
     * @mbg.generated
     */
    public Long getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_id
     *
     * @param refundId the value for od_order_refund.refund_id
     *
     * @mbg.generated
     */
    public void setRefundId(Long refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.order_id
     *
     * @return the value of od_order_refund.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.order_id
     *
     * @param orderId the value for od_order_refund.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.platform_id
     *
     * @return the value of od_order_refund.platform_id
     *
     * @mbg.generated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.platform_id
     *
     * @param platformId the value for od_order_refund.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_total_amount
     *
     * @return the value of od_order_refund.refund_total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRefundTotalAmount() {
        return refundTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_total_amount
     *
     * @param refundTotalAmount the value for od_order_refund.refund_total_amount
     *
     * @mbg.generated
     */
    public void setRefundTotalAmount(BigDecimal refundTotalAmount) {
        this.refundTotalAmount = refundTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_amount_type
     *
     * @return the value of od_order_refund.refund_amount_type
     *
     * @mbg.generated
     */
    public Integer getRefundAmountType() {
        return refundAmountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_amount_type
     *
     * @param refundAmountType the value for od_order_refund.refund_amount_type
     *
     * @mbg.generated
     */
    public void setRefundAmountType(Integer refundAmountType) {
        this.refundAmountType = refundAmountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_status_id
     *
     * @return the value of od_order_refund.refund_status_id
     *
     * @mbg.generated
     */
    public Integer getRefundStatusId() {
        return refundStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_status_id
     *
     * @param refundStatusId the value for od_order_refund.refund_status_id
     *
     * @mbg.generated
     */
    public void setRefundStatusId(Integer refundStatusId) {
        this.refundStatusId = refundStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_handle_admin_id
     *
     * @return the value of od_order_refund.refund_handle_admin_id
     *
     * @mbg.generated
     */
    public Long getRefundHandleAdminId() {
        return refundHandleAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_handle_admin_id
     *
     * @param refundHandleAdminId the value for od_order_refund.refund_handle_admin_id
     *
     * @mbg.generated
     */
    public void setRefundHandleAdminId(Long refundHandleAdminId) {
        this.refundHandleAdminId = refundHandleAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_handle_admin_name
     *
     * @return the value of od_order_refund.refund_handle_admin_name
     *
     * @mbg.generated
     */
    public String getRefundHandleAdminName() {
        return refundHandleAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_handle_admin_name
     *
     * @param refundHandleAdminName the value for od_order_refund.refund_handle_admin_name
     *
     * @mbg.generated
     */
    public void setRefundHandleAdminName(String refundHandleAdminName) {
        this.refundHandleAdminName = refundHandleAdminName == null ? null : refundHandleAdminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_handle_time
     *
     * @return the value of od_order_refund.refund_handle_time
     *
     * @mbg.generated
     */
    public Date getRefundHandleTime() {
        return refundHandleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_handle_time
     *
     * @param refundHandleTime the value for od_order_refund.refund_handle_time
     *
     * @mbg.generated
     */
    public void setRefundHandleTime(Date refundHandleTime) {
        this.refundHandleTime = refundHandleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_handle_content
     *
     * @return the value of od_order_refund.refund_handle_content
     *
     * @mbg.generated
     */
    public String getRefundHandleContent() {
        return refundHandleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_handle_content
     *
     * @param refundHandleContent the value for od_order_refund.refund_handle_content
     *
     * @mbg.generated
     */
    public void setRefundHandleContent(String refundHandleContent) {
        this.refundHandleContent = refundHandleContent == null ? null : refundHandleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_operator
     *
     * @return the value of od_order_refund.refund_operator
     *
     * @mbg.generated
     */
    public Long getRefundOperator() {
        return refundOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_operator
     *
     * @param refundOperator the value for od_order_refund.refund_operator
     *
     * @mbg.generated
     */
    public void setRefundOperator(Long refundOperator) {
        this.refundOperator = refundOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_operator_name
     *
     * @return the value of od_order_refund.refund_operator_name
     *
     * @mbg.generated
     */
    public String getRefundOperatorName() {
        return refundOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_operator_name
     *
     * @param refundOperatorName the value for od_order_refund.refund_operator_name
     *
     * @mbg.generated
     */
    public void setRefundOperatorName(String refundOperatorName) {
        this.refundOperatorName = refundOperatorName == null ? null : refundOperatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_finish_time
     *
     * @return the value of od_order_refund.refund_finish_time
     *
     * @mbg.generated
     */
    public Date getRefundFinishTime() {
        return refundFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_finish_time
     *
     * @param refundFinishTime the value for od_order_refund.refund_finish_time
     *
     * @mbg.generated
     */
    public void setRefundFinishTime(Date refundFinishTime) {
        this.refundFinishTime = refundFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_close_time
     *
     * @return the value of od_order_refund.refund_close_time
     *
     * @mbg.generated
     */
    public Date getRefundCloseTime() {
        return refundCloseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_close_time
     *
     * @param refundCloseTime the value for od_order_refund.refund_close_time
     *
     * @mbg.generated
     */
    public void setRefundCloseTime(Date refundCloseTime) {
        this.refundCloseTime = refundCloseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.invoice_is_return
     *
     * @return the value of od_order_refund.invoice_is_return
     *
     * @mbg.generated
     */
    public Boolean getInvoiceIsReturn() {
        return invoiceIsReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.invoice_is_return
     *
     * @param invoiceIsReturn the value for od_order_refund.invoice_is_return
     *
     * @mbg.generated
     */
    public void setInvoiceIsReturn(Boolean invoiceIsReturn) {
        this.invoiceIsReturn = invoiceIsReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.express_number
     *
     * @return the value of od_order_refund.express_number
     *
     * @mbg.generated
     */
    public String getExpressNumber() {
        return expressNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.express_number
     *
     * @param expressNumber the value for od_order_refund.express_number
     *
     * @mbg.generated
     */
    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber == null ? null : expressNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.express_status
     *
     * @return the value of od_order_refund.express_status
     *
     * @mbg.generated
     */
    public Boolean getExpressStatus() {
        return expressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.express_status
     *
     * @param expressStatus the value for od_order_refund.express_status
     *
     * @mbg.generated
     */
    public void setExpressStatus(Boolean expressStatus) {
        this.expressStatus = expressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_date
     *
     * @return the value of od_order_refund.refund_date
     *
     * @mbg.generated
     */
    public Date getRefundDate() {
        return refundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_date
     *
     * @param refundDate the value for od_order_refund.refund_date
     *
     * @mbg.generated
     */
    public void setRefundDate(Date refundDate) {
        this.refundDate = refundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.refund_batch_no
     *
     * @return the value of od_order_refund.refund_batch_no
     *
     * @mbg.generated
     */
    public String getRefundBatchNo() {
        return refundBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.refund_batch_no
     *
     * @param refundBatchNo the value for od_order_refund.refund_batch_no
     *
     * @mbg.generated
     */
    public void setRefundBatchNo(String refundBatchNo) {
        this.refundBatchNo = refundBatchNo == null ? null : refundBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.creator_type
     *
     * @return the value of od_order_refund.creator_type
     *
     * @mbg.generated
     */
    public Integer getCreatorType() {
        return creatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.creator_type
     *
     * @param creatorType the value for od_order_refund.creator_type
     *
     * @mbg.generated
     */
    public void setCreatorType(Integer creatorType) {
        this.creatorType = creatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.creator
     *
     * @return the value of od_order_refund.creator
     *
     * @mbg.generated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.creator
     *
     * @param creator the value for od_order_refund.creator
     *
     * @mbg.generated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.updated
     *
     * @return the value of od_order_refund.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.updated
     *
     * @param updated the value for od_order_refund.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_refund.created
     *
     * @return the value of od_order_refund.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_refund.created
     *
     * @param created the value for od_order_refund.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}