package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class CJHotPosition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_hot_position.pos_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long posId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_hot_position.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_hot_position.end_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cj_hot_position
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_hot_position.pos_id
     *
     * @return the value of cj_hot_position.pos_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getPosId() {
        return posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_hot_position.pos_id
     *
     * @param posId the value for cj_hot_position.pos_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPosId(Long posId) {
        this.posId = posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_hot_position.create_time
     *
     * @return the value of cj_hot_position.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_hot_position.create_time
     *
     * @param createTime the value for cj_hot_position.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_hot_position.end_time
     *
     * @return the value of cj_hot_position.end_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_hot_position.end_time
     *
     * @param endTime the value for cj_hot_position.end_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cj_hot_position
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", posId=").append(posId);
        sb.append(", createTime=").append(createTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}