package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class CJHotCompany implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_hot_company.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_hot_company.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_hot_company.end_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cj_hot_company
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_hot_company.comp_id
     *
     * @return the value of cj_hot_company.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_hot_company.comp_id
     *
     * @param compId the value for cj_hot_company.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_hot_company.create_time
     *
     * @return the value of cj_hot_company.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_hot_company.create_time
     *
     * @param createTime the value for cj_hot_company.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_hot_company.end_time
     *
     * @return the value of cj_hot_company.end_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_hot_company.end_time
     *
     * @param endTime the value for cj_hot_company.end_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cj_hot_company
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", compId=").append(compId);
        sb.append(", createTime=").append(createTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}