package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class CJResumeCase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.caseid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long caseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long stuUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.resume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long resumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.case_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String caseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.position_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date btime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date etime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.case_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String caseDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.case_duty
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String caseDuty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cj_resume_case.etime_now
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer etimeNow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cj_resume_case
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.caseid
     *
     * @return the value of cj_resume_case.caseid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.caseid
     *
     * @param caseid the value for cj_resume_case.caseid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCaseid(Long caseid) {
        this.caseid = caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.stu_userid
     *
     * @return the value of cj_resume_case.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getStuUserid() {
        return stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.stu_userid
     *
     * @param stuUserid the value for cj_resume_case.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setStuUserid(Long stuUserid) {
        this.stuUserid = stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.resume_id
     *
     * @return the value of cj_resume_case.resume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.resume_id
     *
     * @param resumeId the value for cj_resume_case.resume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.case_name
     *
     * @return the value of cj_resume_case.case_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.case_name
     *
     * @param caseName the value for cj_resume_case.case_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.position_name
     *
     * @return the value of cj_resume_case.position_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.position_name
     *
     * @param positionName the value for cj_resume_case.position_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.btime
     *
     * @return the value of cj_resume_case.btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getBtime() {
        return btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.btime
     *
     * @param btime the value for cj_resume_case.btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setBtime(Date btime) {
        this.btime = btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.etime
     *
     * @return the value of cj_resume_case.etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.etime
     *
     * @param etime the value for cj_resume_case.etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEtime(Date etime) {
        this.etime = etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.case_desc
     *
     * @return the value of cj_resume_case.case_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getCaseDesc() {
        return caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.case_desc
     *
     * @param caseDesc the value for cj_resume_case.case_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCaseDesc(String caseDesc) {
        this.caseDesc = caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.case_duty
     *
     * @return the value of cj_resume_case.case_duty
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getCaseDuty() {
        return caseDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.case_duty
     *
     * @param caseDuty the value for cj_resume_case.case_duty
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCaseDuty(String caseDuty) {
        this.caseDuty = caseDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cj_resume_case.etime_now
     *
     * @return the value of cj_resume_case.etime_now
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getEtimeNow() {
        return etimeNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cj_resume_case.etime_now
     *
     * @param etimeNow the value for cj_resume_case.etime_now
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEtimeNow(Integer etimeNow) {
        this.etimeNow = etimeNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cj_resume_case
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", caseid=").append(caseid);
        sb.append(", stuUserid=").append(stuUserid);
        sb.append(", resumeId=").append(resumeId);
        sb.append(", caseName=").append(caseName);
        sb.append(", positionName=").append(positionName);
        sb.append(", btime=").append(btime);
        sb.append(", etime=").append(etime);
        sb.append(", caseDesc=").append(caseDesc);
        sb.append(", caseDuty=").append(caseDuty);
        sb.append(", etimeNow=").append(etimeNow);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}