package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class CollectionResume implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection_resume.nnid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long nnid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection_resume.dir_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long dirId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection_resume.resume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long resumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection_resume.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long cmUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection_resume.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_collection_resume
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection_resume.nnid
     *
     * @return the value of xz_collection_resume.nnid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getNnid() {
        return nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection_resume.nnid
     *
     * @param nnid the value for xz_collection_resume.nnid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setNnid(Long nnid) {
        this.nnid = nnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection_resume.dir_id
     *
     * @return the value of xz_collection_resume.dir_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getDirId() {
        return dirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection_resume.dir_id
     *
     * @param dirId the value for xz_collection_resume.dir_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setDirId(Long dirId) {
        this.dirId = dirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection_resume.resume_id
     *
     * @return the value of xz_collection_resume.resume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection_resume.resume_id
     *
     * @param resumeId the value for xz_collection_resume.resume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection_resume.cm_userid
     *
     * @return the value of xz_collection_resume.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection_resume.cm_userid
     *
     * @param cmUserid the value for xz_collection_resume.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCmUserid(Long cmUserid) {
        this.cmUserid = cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection_resume.create_time
     *
     * @return the value of xz_collection_resume.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection_resume.create_time
     *
     * @param createTime the value for xz_collection_resume.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_collection_resume
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nnid=").append(nnid);
        sb.append(", dirId=").append(dirId);
        sb.append(", resumeId=").append(resumeId);
        sb.append(", cmUserid=").append(cmUserid);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}