package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class Collection implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection.dir_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long dirId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection.dir_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String dirName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long cmUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_collection.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_collection
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection.dir_id
     *
     * @return the value of xz_collection.dir_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getDirId() {
        return dirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection.dir_id
     *
     * @param dirId the value for xz_collection.dir_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setDirId(Long dirId) {
        this.dirId = dirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection.dir_name
     *
     * @return the value of xz_collection.dir_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getDirName() {
        return dirName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection.dir_name
     *
     * @param dirName the value for xz_collection.dir_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setDirName(String dirName) {
        this.dirName = dirName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection.cm_userid
     *
     * @return the value of xz_collection.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection.cm_userid
     *
     * @param cmUserid the value for xz_collection.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCmUserid(Long cmUserid) {
        this.cmUserid = cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_collection.create_time
     *
     * @return the value of xz_collection.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_collection.create_time
     *
     * @param createTime the value for xz_collection.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_collection
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dirId=").append(dirId);
        sb.append(", dirName=").append(dirName);
        sb.append(", cmUserid=").append(cmUserid);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}