package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class CompanyUser2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long cmUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.role_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.user_realname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String userRealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.positon
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String positon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.sso_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long ssoUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.valid_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer validStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.user_phone
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_user.user_email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_company_user
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.cm_userid
     *
     * @return the value of xz_company_user.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.cm_userid
     *
     * @param cmUserid the value for xz_company_user.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCmUserid(Long cmUserid) {
        this.cmUserid = cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.comp_id
     *
     * @return the value of xz_company_user.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.comp_id
     *
     * @param compId the value for xz_company_user.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.role_id
     *
     * @return the value of xz_company_user.role_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.role_id
     *
     * @param roleId the value for xz_company_user.role_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.user_realname
     *
     * @return the value of xz_company_user.user_realname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getUserRealname() {
        return userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.user_realname
     *
     * @param userRealname the value for xz_company_user.user_realname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.positon
     *
     * @return the value of xz_company_user.positon
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getPositon() {
        return positon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.positon
     *
     * @param positon the value for xz_company_user.positon
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPositon(String positon) {
        this.positon = positon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.sso_userid
     *
     * @return the value of xz_company_user.sso_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getSsoUserid() {
        return ssoUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.sso_userid
     *
     * @param ssoUserid the value for xz_company_user.sso_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setSsoUserid(Long ssoUserid) {
        this.ssoUserid = ssoUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.valid_status
     *
     * @return the value of xz_company_user.valid_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getValidStatus() {
        return validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.valid_status
     *
     * @param validStatus the value for xz_company_user.valid_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setValidStatus(Integer validStatus) {
        this.validStatus = validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.user_phone
     *
     * @return the value of xz_company_user.user_phone
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.user_phone
     *
     * @param userPhone the value for xz_company_user.user_phone
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_user.user_email
     *
     * @return the value of xz_company_user.user_email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_user.user_email
     *
     * @param userEmail the value for xz_company_user.user_email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_company_user
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cmUserid=").append(cmUserid);
        sb.append(", compId=").append(compId);
        sb.append(", roleId=").append(roleId);
        sb.append(", userRealname=").append(userRealname);
        sb.append(", positon=").append(positon);
        sb.append(", ssoUserid=").append(ssoUserid);
        sb.append(", validStatus=").append(validStatus);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}