package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class CompanyDescription implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_description.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_description.title
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_description.isopen
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer isopen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_description.comany_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String comanyDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_company_description
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_description.comp_id
     *
     * @return the value of xz_company_description.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_description.comp_id
     *
     * @param compId the value for xz_company_description.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_description.title
     *
     * @return the value of xz_company_description.title
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_description.title
     *
     * @param title the value for xz_company_description.title
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_description.isopen
     *
     * @return the value of xz_company_description.isopen
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getIsopen() {
        return isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_description.isopen
     *
     * @param isopen the value for xz_company_description.isopen
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setIsopen(Integer isopen) {
        this.isopen = isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_description.comany_desc
     *
     * @return the value of xz_company_description.comany_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getComanyDesc() {
        return comanyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_description.comany_desc
     *
     * @param comanyDesc the value for xz_company_description.comany_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setComanyDesc(String comanyDesc) {
        this.comanyDesc = comanyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_company_description
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", compId=").append(compId);
        sb.append(", title=").append(title);
        sb.append(", isopen=").append(isopen);
        sb.append(", comanyDesc=").append(comanyDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}