package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class Company implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.company_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.short_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.add_user_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer addUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.add_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.industry_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer industryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer scaleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.img
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.contact_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.contact_tel
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String contactTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.contact_email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String contactEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.contact_weixin
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String contactWeixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.finance_info_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer financeInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.loginname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.position_count
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer positionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.wangshen_open
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer wangshenOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.wangshen_btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date wangshenBtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.wangshen_etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date wangshenEtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.wangshen_termid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer wangshenTermid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.audit_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.audit_msg
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String auditMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company.deal_img
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String dealImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_company
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.comp_id
     *
     * @return the value of xz_company.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.comp_id
     *
     * @param compId the value for xz_company.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.company_name
     *
     * @return the value of xz_company.company_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.company_name
     *
     * @param companyName the value for xz_company.company_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.short_name
     *
     * @return the value of xz_company.short_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.short_name
     *
     * @param shortName the value for xz_company.short_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.add_user_id
     *
     * @return the value of xz_company.add_user_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.add_user_id
     *
     * @param addUserId the value for xz_company.add_user_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setAddUserId(Integer addUserId) {
        this.addUserId = addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.add_time
     *
     * @return the value of xz_company.add_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.add_time
     *
     * @param addTime the value for xz_company.add_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.industry_id
     *
     * @return the value of xz_company.industry_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.industry_id
     *
     * @param industryId the value for xz_company.industry_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.scale_id
     *
     * @return the value of xz_company.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.scale_id
     *
     * @param scaleId the value for xz_company.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setScaleId(Integer scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.img
     *
     * @return the value of xz_company.img
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.img
     *
     * @param img the value for xz_company.img
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.contact_name
     *
     * @return the value of xz_company.contact_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.contact_name
     *
     * @param contactName the value for xz_company.contact_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.contact_tel
     *
     * @return the value of xz_company.contact_tel
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.contact_tel
     *
     * @param contactTel the value for xz_company.contact_tel
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.contact_email
     *
     * @return the value of xz_company.contact_email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.contact_email
     *
     * @param contactEmail the value for xz_company.contact_email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.contact_weixin
     *
     * @return the value of xz_company.contact_weixin
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getContactWeixin() {
        return contactWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.contact_weixin
     *
     * @param contactWeixin the value for xz_company.contact_weixin
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setContactWeixin(String contactWeixin) {
        this.contactWeixin = contactWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.finance_info_id
     *
     * @return the value of xz_company.finance_info_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getFinanceInfoId() {
        return financeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.finance_info_id
     *
     * @param financeInfoId the value for xz_company.finance_info_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setFinanceInfoId(Integer financeInfoId) {
        this.financeInfoId = financeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.loginname
     *
     * @return the value of xz_company.loginname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.loginname
     *
     * @param loginname the value for xz_company.loginname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.position_count
     *
     * @return the value of xz_company.position_count
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getPositionCount() {
        return positionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.position_count
     *
     * @param positionCount the value for xz_company.position_count
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPositionCount(Integer positionCount) {
        this.positionCount = positionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.wangshen_open
     *
     * @return the value of xz_company.wangshen_open
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getWangshenOpen() {
        return wangshenOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.wangshen_open
     *
     * @param wangshenOpen the value for xz_company.wangshen_open
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWangshenOpen(Integer wangshenOpen) {
        this.wangshenOpen = wangshenOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.wangshen_btime
     *
     * @return the value of xz_company.wangshen_btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getWangshenBtime() {
        return wangshenBtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.wangshen_btime
     *
     * @param wangshenBtime the value for xz_company.wangshen_btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWangshenBtime(Date wangshenBtime) {
        this.wangshenBtime = wangshenBtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.wangshen_etime
     *
     * @return the value of xz_company.wangshen_etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getWangshenEtime() {
        return wangshenEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.wangshen_etime
     *
     * @param wangshenEtime the value for xz_company.wangshen_etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWangshenEtime(Date wangshenEtime) {
        this.wangshenEtime = wangshenEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.wangshen_termid
     *
     * @return the value of xz_company.wangshen_termid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getWangshenTermid() {
        return wangshenTermid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.wangshen_termid
     *
     * @param wangshenTermid the value for xz_company.wangshen_termid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWangshenTermid(Integer wangshenTermid) {
        this.wangshenTermid = wangshenTermid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.audit_status
     *
     * @return the value of xz_company.audit_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.audit_status
     *
     * @param auditStatus the value for xz_company.audit_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.audit_msg
     *
     * @return the value of xz_company.audit_msg
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getAuditMsg() {
        return auditMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.audit_msg
     *
     * @param auditMsg the value for xz_company.audit_msg
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setAuditMsg(String auditMsg) {
        this.auditMsg = auditMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company.deal_img
     *
     * @return the value of xz_company.deal_img
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getDealImg() {
        return dealImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company.deal_img
     *
     * @param dealImg the value for xz_company.deal_img
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setDealImg(String dealImg) {
        this.dealImg = dealImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_company
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", compId=").append(compId);
        sb.append(", companyName=").append(companyName);
        sb.append(", shortName=").append(shortName);
        sb.append(", addUserId=").append(addUserId);
        sb.append(", addTime=").append(addTime);
        sb.append(", industryId=").append(industryId);
        sb.append(", scaleId=").append(scaleId);
        sb.append(", img=").append(img);
        sb.append(", contactName=").append(contactName);
        sb.append(", contactTel=").append(contactTel);
        sb.append(", contactEmail=").append(contactEmail);
        sb.append(", contactWeixin=").append(contactWeixin);
        sb.append(", financeInfoId=").append(financeInfoId);
        sb.append(", loginname=").append(loginname);
        sb.append(", positionCount=").append(positionCount);
        sb.append(", wangshenOpen=").append(wangshenOpen);
        sb.append(", wangshenBtime=").append(wangshenBtime);
        sb.append(", wangshenEtime=").append(wangshenEtime);
        sb.append(", wangshenTermid=").append(wangshenTermid);
        sb.append(", auditStatus=").append(auditStatus);
        sb.append(", auditMsg=").append(auditMsg);
        sb.append(", dealImg=").append(dealImg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}