package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class CompanyTemplateEmail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.tpl_emailid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long tplEmailid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.phaseid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer phaseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.tpl_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String tplName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.email_title
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String emailTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.isvalid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer isvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long cmUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_template_email.email_content
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String emailContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_company_template_email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.tpl_emailid
     *
     * @return the value of xz_company_template_email.tpl_emailid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getTplEmailid() {
        return tplEmailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.tpl_emailid
     *
     * @param tplEmailid the value for xz_company_template_email.tpl_emailid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setTplEmailid(Long tplEmailid) {
        this.tplEmailid = tplEmailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.comp_id
     *
     * @return the value of xz_company_template_email.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.comp_id
     *
     * @param compId the value for xz_company_template_email.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.phaseid
     *
     * @return the value of xz_company_template_email.phaseid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getPhaseid() {
        return phaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.phaseid
     *
     * @param phaseid the value for xz_company_template_email.phaseid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPhaseid(Integer phaseid) {
        this.phaseid = phaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.tpl_name
     *
     * @return the value of xz_company_template_email.tpl_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getTplName() {
        return tplName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.tpl_name
     *
     * @param tplName the value for xz_company_template_email.tpl_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setTplName(String tplName) {
        this.tplName = tplName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.email_title
     *
     * @return the value of xz_company_template_email.email_title
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getEmailTitle() {
        return emailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.email_title
     *
     * @param emailTitle the value for xz_company_template_email.email_title
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEmailTitle(String emailTitle) {
        this.emailTitle = emailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.isvalid
     *
     * @return the value of xz_company_template_email.isvalid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.isvalid
     *
     * @param isvalid the value for xz_company_template_email.isvalid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.cm_userid
     *
     * @return the value of xz_company_template_email.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.cm_userid
     *
     * @param cmUserid the value for xz_company_template_email.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCmUserid(Long cmUserid) {
        this.cmUserid = cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.create_time
     *
     * @return the value of xz_company_template_email.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.create_time
     *
     * @param createTime the value for xz_company_template_email.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_template_email.email_content
     *
     * @return the value of xz_company_template_email.email_content
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getEmailContent() {
        return emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_template_email.email_content
     *
     * @param emailContent the value for xz_company_template_email.email_content
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_company_template_email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tplEmailid=").append(tplEmailid);
        sb.append(", compId=").append(compId);
        sb.append(", phaseid=").append(phaseid);
        sb.append(", tplName=").append(tplName);
        sb.append(", emailTitle=").append(emailTitle);
        sb.append(", isvalid=").append(isvalid);
        sb.append(", cmUserid=").append(cmUserid);
        sb.append(", createTime=").append(createTime);
        sb.append(", emailContent=").append(emailContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}