package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class CompanyInterviewSite implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.insite_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long insiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.site_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String siteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.begin_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.address
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.examiner
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String examiner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long cmUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.nstatus
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer nstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_company_interview_site.desc_text
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String descText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_company_interview_site
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.insite_id
     *
     * @return the value of xz_company_interview_site.insite_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getInsiteId() {
        return insiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.insite_id
     *
     * @param insiteId the value for xz_company_interview_site.insite_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setInsiteId(Long insiteId) {
        this.insiteId = insiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.comp_id
     *
     * @return the value of xz_company_interview_site.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.comp_id
     *
     * @param compId the value for xz_company_interview_site.comp_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.site_name
     *
     * @return the value of xz_company_interview_site.site_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.site_name
     *
     * @param siteName the value for xz_company_interview_site.site_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.begin_time
     *
     * @return the value of xz_company_interview_site.begin_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.begin_time
     *
     * @param beginTime the value for xz_company_interview_site.begin_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.address
     *
     * @return the value of xz_company_interview_site.address
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.address
     *
     * @param address the value for xz_company_interview_site.address
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.examiner
     *
     * @return the value of xz_company_interview_site.examiner
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getExaminer() {
        return examiner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.examiner
     *
     * @param examiner the value for xz_company_interview_site.examiner
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setExaminer(String examiner) {
        this.examiner = examiner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.cm_userid
     *
     * @return the value of xz_company_interview_site.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.cm_userid
     *
     * @param cmUserid the value for xz_company_interview_site.cm_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCmUserid(Long cmUserid) {
        this.cmUserid = cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.nstatus
     *
     * @return the value of xz_company_interview_site.nstatus
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getNstatus() {
        return nstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.nstatus
     *
     * @param nstatus the value for xz_company_interview_site.nstatus
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setNstatus(Integer nstatus) {
        this.nstatus = nstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_company_interview_site.desc_text
     *
     * @return the value of xz_company_interview_site.desc_text
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getDescText() {
        return descText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_company_interview_site.desc_text
     *
     * @param descText the value for xz_company_interview_site.desc_text
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setDescText(String descText) {
        this.descText = descText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_company_interview_site
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", insiteId=").append(insiteId);
        sb.append(", compId=").append(compId);
        sb.append(", siteName=").append(siteName);
        sb.append(", beginTime=").append(beginTime);
        sb.append(", address=").append(address);
        sb.append(", examiner=").append(examiner);
        sb.append(", cmUserid=").append(cmUserid);
        sb.append(", nstatus=").append(nstatus);
        sb.append(", descText=").append(descText);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}