package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class DictWorkexp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_workexp.expid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long expid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_workexp.exp_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String expName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_workexp.year_min
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer yearMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_workexp.year_max
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer yearMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_dict_workexp
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_workexp.expid
     *
     * @return the value of xz_dict_workexp.expid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getExpid() {
        return expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_workexp.expid
     *
     * @param expid the value for xz_dict_workexp.expid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setExpid(Long expid) {
        this.expid = expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_workexp.exp_name
     *
     * @return the value of xz_dict_workexp.exp_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getExpName() {
        return expName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_workexp.exp_name
     *
     * @param expName the value for xz_dict_workexp.exp_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setExpName(String expName) {
        this.expName = expName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_workexp.year_min
     *
     * @return the value of xz_dict_workexp.year_min
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getYearMin() {
        return yearMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_workexp.year_min
     *
     * @param yearMin the value for xz_dict_workexp.year_min
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setYearMin(Integer yearMin) {
        this.yearMin = yearMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_workexp.year_max
     *
     * @return the value of xz_dict_workexp.year_max
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getYearMax() {
        return yearMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_workexp.year_max
     *
     * @param yearMax the value for xz_dict_workexp.year_max
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setYearMax(Integer yearMax) {
        this.yearMax = yearMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_dict_workexp
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", expid=").append(expid);
        sb.append(", expName=").append(expName);
        sb.append(", yearMin=").append(yearMin);
        sb.append(", yearMax=").append(yearMax);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}