package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class DictEducation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_education.edu_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer eduId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_education.edu_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String eduName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_dict_education
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_education.edu_id
     *
     * @return the value of xz_dict_education.edu_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getEduId() {
        return eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_education.edu_id
     *
     * @param eduId the value for xz_dict_education.edu_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEduId(Integer eduId) {
        this.eduId = eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_education.edu_name
     *
     * @return the value of xz_dict_education.edu_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getEduName() {
        return eduName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_education.edu_name
     *
     * @param eduName the value for xz_dict_education.edu_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEduName(String eduName) {
        this.eduName = eduName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_dict_education
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eduId=").append(eduId);
        sb.append(", eduName=").append(eduName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}