package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class DictComputorlevel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_computorlevel.cid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_computorlevel.name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_dict_computorlevel
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_computorlevel.cid
     *
     * @return the value of xz_dict_computorlevel.cid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_computorlevel.cid
     *
     * @param cid the value for xz_dict_computorlevel.cid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_computorlevel.name
     *
     * @return the value of xz_dict_computorlevel.name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_computorlevel.name
     *
     * @param name the value for xz_dict_computorlevel.name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_dict_computorlevel
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}