package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class DictPostype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_postype.pos_typeid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer posTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_postype.pos_typename
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String posTypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_postype.pid_typeid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer pidTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_postype.ishot
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer ishot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_dict_postype
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_postype.pos_typeid
     *
     * @return the value of xz_dict_postype.pos_typeid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getPosTypeid() {
        return posTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_postype.pos_typeid
     *
     * @param posTypeid the value for xz_dict_postype.pos_typeid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPosTypeid(Integer posTypeid) {
        this.posTypeid = posTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_postype.pos_typename
     *
     * @return the value of xz_dict_postype.pos_typename
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getPosTypename() {
        return posTypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_postype.pos_typename
     *
     * @param posTypename the value for xz_dict_postype.pos_typename
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPosTypename(String posTypename) {
        this.posTypename = posTypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_postype.pid_typeid
     *
     * @return the value of xz_dict_postype.pid_typeid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getPidTypeid() {
        return pidTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_postype.pid_typeid
     *
     * @param pidTypeid the value for xz_dict_postype.pid_typeid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPidTypeid(Integer pidTypeid) {
        this.pidTypeid = pidTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_postype.ishot
     *
     * @return the value of xz_dict_postype.ishot
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_postype.ishot
     *
     * @param ishot the value for xz_dict_postype.ishot
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setIshot(Integer ishot) {
        this.ishot = ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_dict_postype
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", posTypeid=").append(posTypeid);
        sb.append(", posTypename=").append(posTypename);
        sb.append(", pidTypeid=").append(pidTypeid);
        sb.append(", ishot=").append(ishot);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}