package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class DictScale implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_scale.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long scaleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_scale.name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_dict_scale
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_scale.scale_id
     *
     * @return the value of xz_dict_scale.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_scale.scale_id
     *
     * @param scaleId the value for xz_dict_scale.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setScaleId(Long scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_scale.name
     *
     * @return the value of xz_dict_scale.name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_scale.name
     *
     * @param name the value for xz_dict_scale.name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_dict_scale
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scaleId=").append(scaleId);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}