package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class DictCounty implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_county.cities_county_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long citiesCountyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_county.cities_city_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long citiesCityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_county.cities_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String citiesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_county.cities_level
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String citiesLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_county.is_valid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_dict_county.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_dict_county
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_county.cities_county_code
     *
     * @return the value of xz_dict_county.cities_county_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCitiesCountyCode() {
        return citiesCountyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_county.cities_county_code
     *
     * @param citiesCountyCode the value for xz_dict_county.cities_county_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCitiesCountyCode(Long citiesCountyCode) {
        this.citiesCountyCode = citiesCountyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_county.cities_city_code
     *
     * @return the value of xz_dict_county.cities_city_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCitiesCityCode() {
        return citiesCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_county.cities_city_code
     *
     * @param citiesCityCode the value for xz_dict_county.cities_city_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCitiesCityCode(Long citiesCityCode) {
        this.citiesCityCode = citiesCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_county.cities_name
     *
     * @return the value of xz_dict_county.cities_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getCitiesName() {
        return citiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_county.cities_name
     *
     * @param citiesName the value for xz_dict_county.cities_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCitiesName(String citiesName) {
        this.citiesName = citiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_county.cities_level
     *
     * @return the value of xz_dict_county.cities_level
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getCitiesLevel() {
        return citiesLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_county.cities_level
     *
     * @param citiesLevel the value for xz_dict_county.cities_level
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCitiesLevel(String citiesLevel) {
        this.citiesLevel = citiesLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_county.is_valid
     *
     * @return the value of xz_dict_county.is_valid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_county.is_valid
     *
     * @param isValid the value for xz_dict_county.is_valid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_dict_county.create_time
     *
     * @return the value of xz_dict_county.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_dict_county.create_time
     *
     * @param createTime the value for xz_dict_county.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_dict_county
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", citiesCountyCode=").append(citiesCountyCode);
        sb.append(", citiesCityCode=").append(citiesCityCode);
        sb.append(", citiesName=").append(citiesName);
        sb.append(", citiesLevel=").append(citiesLevel);
        sb.append(", isValid=").append(isValid);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}