package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class ExamResult implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_exam_result.resultid
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private Long resultid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_exam_result.user_name
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_exam_result.phone
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_exam_result.email
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_exam_result.college_name
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private String collegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_exam_result.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_exam_result.compid
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private Long compid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_exam_result.result_score
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private Float resultScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_exam_result
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_exam_result.resultid
     *
     * @return the value of xz_exam_result.resultid
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public Long getResultid() {
        return resultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_exam_result.resultid
     *
     * @param resultid the value for xz_exam_result.resultid
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public void setResultid(Long resultid) {
        this.resultid = resultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_exam_result.user_name
     *
     * @return the value of xz_exam_result.user_name
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_exam_result.user_name
     *
     * @param userName the value for xz_exam_result.user_name
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_exam_result.phone
     *
     * @return the value of xz_exam_result.phone
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_exam_result.phone
     *
     * @param phone the value for xz_exam_result.phone
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_exam_result.email
     *
     * @return the value of xz_exam_result.email
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_exam_result.email
     *
     * @param email the value for xz_exam_result.email
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_exam_result.college_name
     *
     * @return the value of xz_exam_result.college_name
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_exam_result.college_name
     *
     * @param collegeName the value for xz_exam_result.college_name
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_exam_result.create_time
     *
     * @return the value of xz_exam_result.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_exam_result.create_time
     *
     * @param createTime the value for xz_exam_result.create_time
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_exam_result.compid
     *
     * @return the value of xz_exam_result.compid
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public Long getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_exam_result.compid
     *
     * @param compid the value for xz_exam_result.compid
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public void setCompid(Long compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_exam_result.result_score
     *
     * @return the value of xz_exam_result.result_score
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public Float getResultScore() {
        return resultScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_exam_result.result_score
     *
     * @param resultScore the value for xz_exam_result.result_score
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    public void setResultScore(Float resultScore) {
        this.resultScore = resultScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_exam_result
     *
     * @mbg.generated Tue Aug 27 14:36:33 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resultid=").append(resultid);
        sb.append(", userName=").append(userName);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", collegeName=").append(collegeName);
        sb.append(", createTime=").append(createTime);
        sb.append(", compid=").append(compid);
        sb.append(", resultScore=").append(resultScore);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}