package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class MyResume implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long myresumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.province_cities_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long provinceCitiesCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.cities_city_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long citiesCityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.province_code_reside
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long provinceCodeReside;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.city_code_reside
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long cityCodeReside;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long stuUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.submit_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.user_realname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String userRealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.tel
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.sex
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.nation
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.birth
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.marriage
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.ident_type
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer identType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.ident_no
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String identNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.politics_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer politicsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.wish_position
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String wishPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.wish_province_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long wishProvinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.wish_city_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long wishCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.wish_max_salary
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer wishMaxSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.wish_min_salary
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer wishMinSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.job_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer jobStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.self_evaluation
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String selfEvaluation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.faceurl
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String faceurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.start_work_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date startWorkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.computer_level
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer computerLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.resume_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String resumeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.major_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.major_pid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer majorPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.college_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long collegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.edu_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long eduId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.wish_pos_typeid3
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer wishPosTypeid3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.wish_pos_typeid2
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer wishPosTypeid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.wish_pos_typeid1
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer wishPosTypeid1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume.college_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String collegeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_resume
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.myresume_id
     *
     * @return the value of my_resume.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getMyresumeId() {
        return myresumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.myresume_id
     *
     * @param myresumeId the value for my_resume.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setMyresumeId(Long myresumeId) {
        this.myresumeId = myresumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.province_cities_code
     *
     * @return the value of my_resume.province_cities_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getProvinceCitiesCode() {
        return provinceCitiesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.province_cities_code
     *
     * @param provinceCitiesCode the value for my_resume.province_cities_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setProvinceCitiesCode(Long provinceCitiesCode) {
        this.provinceCitiesCode = provinceCitiesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.cities_city_code
     *
     * @return the value of my_resume.cities_city_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCitiesCityCode() {
        return citiesCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.cities_city_code
     *
     * @param citiesCityCode the value for my_resume.cities_city_code
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCitiesCityCode(Long citiesCityCode) {
        this.citiesCityCode = citiesCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.province_code_reside
     *
     * @return the value of my_resume.province_code_reside
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getProvinceCodeReside() {
        return provinceCodeReside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.province_code_reside
     *
     * @param provinceCodeReside the value for my_resume.province_code_reside
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setProvinceCodeReside(Long provinceCodeReside) {
        this.provinceCodeReside = provinceCodeReside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.city_code_reside
     *
     * @return the value of my_resume.city_code_reside
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCityCodeReside() {
        return cityCodeReside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.city_code_reside
     *
     * @param cityCodeReside the value for my_resume.city_code_reside
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCityCodeReside(Long cityCodeReside) {
        this.cityCodeReside = cityCodeReside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.stu_userid
     *
     * @return the value of my_resume.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getStuUserid() {
        return stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.stu_userid
     *
     * @param stuUserid the value for my_resume.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setStuUserid(Long stuUserid) {
        this.stuUserid = stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.submit_time
     *
     * @return the value of my_resume.submit_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.submit_time
     *
     * @param submitTime the value for my_resume.submit_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.user_realname
     *
     * @return the value of my_resume.user_realname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getUserRealname() {
        return userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.user_realname
     *
     * @param userRealname the value for my_resume.user_realname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.tel
     *
     * @return the value of my_resume.tel
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.tel
     *
     * @param tel the value for my_resume.tel
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.email
     *
     * @return the value of my_resume.email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.email
     *
     * @param email the value for my_resume.email
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.sex
     *
     * @return the value of my_resume.sex
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.sex
     *
     * @param sex the value for my_resume.sex
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.nation
     *
     * @return the value of my_resume.nation
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.nation
     *
     * @param nation the value for my_resume.nation
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.birth
     *
     * @return the value of my_resume.birth
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.birth
     *
     * @param birth the value for my_resume.birth
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.marriage
     *
     * @return the value of my_resume.marriage
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.marriage
     *
     * @param marriage the value for my_resume.marriage
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setMarriage(Integer marriage) {
        this.marriage = marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.ident_type
     *
     * @return the value of my_resume.ident_type
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getIdentType() {
        return identType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.ident_type
     *
     * @param identType the value for my_resume.ident_type
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setIdentType(Integer identType) {
        this.identType = identType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.ident_no
     *
     * @return the value of my_resume.ident_no
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getIdentNo() {
        return identNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.ident_no
     *
     * @param identNo the value for my_resume.ident_no
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setIdentNo(String identNo) {
        this.identNo = identNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.politics_id
     *
     * @return the value of my_resume.politics_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getPoliticsId() {
        return politicsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.politics_id
     *
     * @param politicsId the value for my_resume.politics_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPoliticsId(Integer politicsId) {
        this.politicsId = politicsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.wish_position
     *
     * @return the value of my_resume.wish_position
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getWishPosition() {
        return wishPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.wish_position
     *
     * @param wishPosition the value for my_resume.wish_position
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWishPosition(String wishPosition) {
        this.wishPosition = wishPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.wish_province_id
     *
     * @return the value of my_resume.wish_province_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getWishProvinceId() {
        return wishProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.wish_province_id
     *
     * @param wishProvinceId the value for my_resume.wish_province_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWishProvinceId(Long wishProvinceId) {
        this.wishProvinceId = wishProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.wish_city_id
     *
     * @return the value of my_resume.wish_city_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getWishCityId() {
        return wishCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.wish_city_id
     *
     * @param wishCityId the value for my_resume.wish_city_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWishCityId(Long wishCityId) {
        this.wishCityId = wishCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.wish_max_salary
     *
     * @return the value of my_resume.wish_max_salary
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getWishMaxSalary() {
        return wishMaxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.wish_max_salary
     *
     * @param wishMaxSalary the value for my_resume.wish_max_salary
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWishMaxSalary(Integer wishMaxSalary) {
        this.wishMaxSalary = wishMaxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.wish_min_salary
     *
     * @return the value of my_resume.wish_min_salary
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getWishMinSalary() {
        return wishMinSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.wish_min_salary
     *
     * @param wishMinSalary the value for my_resume.wish_min_salary
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWishMinSalary(Integer wishMinSalary) {
        this.wishMinSalary = wishMinSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.job_status
     *
     * @return the value of my_resume.job_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.job_status
     *
     * @param jobStatus the value for my_resume.job_status
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setJobStatus(Integer jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.self_evaluation
     *
     * @return the value of my_resume.self_evaluation
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getSelfEvaluation() {
        return selfEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.self_evaluation
     *
     * @param selfEvaluation the value for my_resume.self_evaluation
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setSelfEvaluation(String selfEvaluation) {
        this.selfEvaluation = selfEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.faceurl
     *
     * @return the value of my_resume.faceurl
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getFaceurl() {
        return faceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.faceurl
     *
     * @param faceurl the value for my_resume.faceurl
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setFaceurl(String faceurl) {
        this.faceurl = faceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.start_work_time
     *
     * @return the value of my_resume.start_work_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getStartWorkTime() {
        return startWorkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.start_work_time
     *
     * @param startWorkTime the value for my_resume.start_work_time
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setStartWorkTime(Date startWorkTime) {
        this.startWorkTime = startWorkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.computer_level
     *
     * @return the value of my_resume.computer_level
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getComputerLevel() {
        return computerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.computer_level
     *
     * @param computerLevel the value for my_resume.computer_level
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setComputerLevel(Integer computerLevel) {
        this.computerLevel = computerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.resume_name
     *
     * @return the value of my_resume.resume_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getResumeName() {
        return resumeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.resume_name
     *
     * @param resumeName the value for my_resume.resume_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setResumeName(String resumeName) {
        this.resumeName = resumeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.major_id
     *
     * @return the value of my_resume.major_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.major_id
     *
     * @param majorId the value for my_resume.major_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.major_pid
     *
     * @return the value of my_resume.major_pid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getMajorPid() {
        return majorPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.major_pid
     *
     * @param majorPid the value for my_resume.major_pid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setMajorPid(Integer majorPid) {
        this.majorPid = majorPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.college_id
     *
     * @return the value of my_resume.college_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.college_id
     *
     * @param collegeId the value for my_resume.college_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCollegeId(Long collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.edu_id
     *
     * @return the value of my_resume.edu_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getEduId() {
        return eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.edu_id
     *
     * @param eduId the value for my_resume.edu_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEduId(Long eduId) {
        this.eduId = eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.wish_pos_typeid3
     *
     * @return the value of my_resume.wish_pos_typeid3
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getWishPosTypeid3() {
        return wishPosTypeid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.wish_pos_typeid3
     *
     * @param wishPosTypeid3 the value for my_resume.wish_pos_typeid3
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWishPosTypeid3(Integer wishPosTypeid3) {
        this.wishPosTypeid3 = wishPosTypeid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.wish_pos_typeid2
     *
     * @return the value of my_resume.wish_pos_typeid2
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getWishPosTypeid2() {
        return wishPosTypeid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.wish_pos_typeid2
     *
     * @param wishPosTypeid2 the value for my_resume.wish_pos_typeid2
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWishPosTypeid2(Integer wishPosTypeid2) {
        this.wishPosTypeid2 = wishPosTypeid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.wish_pos_typeid1
     *
     * @return the value of my_resume.wish_pos_typeid1
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getWishPosTypeid1() {
        return wishPosTypeid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.wish_pos_typeid1
     *
     * @param wishPosTypeid1 the value for my_resume.wish_pos_typeid1
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWishPosTypeid1(Integer wishPosTypeid1) {
        this.wishPosTypeid1 = wishPosTypeid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume.college_name
     *
     * @return the value of my_resume.college_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume.college_name
     *
     * @param collegeName the value for my_resume.college_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_resume
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", myresumeId=").append(myresumeId);
        sb.append(", provinceCitiesCode=").append(provinceCitiesCode);
        sb.append(", citiesCityCode=").append(citiesCityCode);
        sb.append(", provinceCodeReside=").append(provinceCodeReside);
        sb.append(", cityCodeReside=").append(cityCodeReside);
        sb.append(", stuUserid=").append(stuUserid);
        sb.append(", submitTime=").append(submitTime);
        sb.append(", userRealname=").append(userRealname);
        sb.append(", tel=").append(tel);
        sb.append(", email=").append(email);
        sb.append(", sex=").append(sex);
        sb.append(", nation=").append(nation);
        sb.append(", birth=").append(birth);
        sb.append(", marriage=").append(marriage);
        sb.append(", identType=").append(identType);
        sb.append(", identNo=").append(identNo);
        sb.append(", politicsId=").append(politicsId);
        sb.append(", wishPosition=").append(wishPosition);
        sb.append(", wishProvinceId=").append(wishProvinceId);
        sb.append(", wishCityId=").append(wishCityId);
        sb.append(", wishMaxSalary=").append(wishMaxSalary);
        sb.append(", wishMinSalary=").append(wishMinSalary);
        sb.append(", jobStatus=").append(jobStatus);
        sb.append(", selfEvaluation=").append(selfEvaluation);
        sb.append(", faceurl=").append(faceurl);
        sb.append(", startWorkTime=").append(startWorkTime);
        sb.append(", computerLevel=").append(computerLevel);
        sb.append(", resumeName=").append(resumeName);
        sb.append(", majorId=").append(majorId);
        sb.append(", majorPid=").append(majorPid);
        sb.append(", collegeId=").append(collegeId);
        sb.append(", eduId=").append(eduId);
        sb.append(", wishPosTypeid3=").append(wishPosTypeid3);
        sb.append(", wishPosTypeid2=").append(wishPosTypeid2);
        sb.append(", wishPosTypeid1=").append(wishPosTypeid1);
        sb.append(", collegeName=").append(collegeName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}