package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class MyResumeAward implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_award.resume_awardid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long resumeAwardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_award.award_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String awardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_award.award_strdate
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String awardStrdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_award.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long stuUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_award.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long myresumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_resume_award
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_award.resume_awardid
     *
     * @return the value of my_resume_award.resume_awardid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getResumeAwardid() {
        return resumeAwardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_award.resume_awardid
     *
     * @param resumeAwardid the value for my_resume_award.resume_awardid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setResumeAwardid(Long resumeAwardid) {
        this.resumeAwardid = resumeAwardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_award.award_name
     *
     * @return the value of my_resume_award.award_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_award.award_name
     *
     * @param awardName the value for my_resume_award.award_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_award.award_strdate
     *
     * @return the value of my_resume_award.award_strdate
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getAwardStrdate() {
        return awardStrdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_award.award_strdate
     *
     * @param awardStrdate the value for my_resume_award.award_strdate
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setAwardStrdate(String awardStrdate) {
        this.awardStrdate = awardStrdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_award.stu_userid
     *
     * @return the value of my_resume_award.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getStuUserid() {
        return stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_award.stu_userid
     *
     * @param stuUserid the value for my_resume_award.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setStuUserid(Long stuUserid) {
        this.stuUserid = stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_award.myresume_id
     *
     * @return the value of my_resume_award.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getMyresumeId() {
        return myresumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_award.myresume_id
     *
     * @param myresumeId the value for my_resume_award.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setMyresumeId(Long myresumeId) {
        this.myresumeId = myresumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_resume_award
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resumeAwardid=").append(resumeAwardid);
        sb.append(", awardName=").append(awardName);
        sb.append(", awardStrdate=").append(awardStrdate);
        sb.append(", stuUserid=").append(stuUserid);
        sb.append(", myresumeId=").append(myresumeId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}