package com.lanqiao.model.zhaopin;

import java.io.Serializable;
import java.util.Date;

public class MyResumeWorkexperience implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.resume_workid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long resumeWorkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long scaleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long stuUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.industry_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer industryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.company_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date btime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Date etime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.depname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String depname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.position_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.work_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String workDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long myresumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_resume_workexperience.etime_now
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Integer etimeNow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_resume_workexperience
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.resume_workid
     *
     * @return the value of my_resume_workexperience.resume_workid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getResumeWorkid() {
        return resumeWorkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.resume_workid
     *
     * @param resumeWorkid the value for my_resume_workexperience.resume_workid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setResumeWorkid(Long resumeWorkid) {
        this.resumeWorkid = resumeWorkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.scale_id
     *
     * @return the value of my_resume_workexperience.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.scale_id
     *
     * @param scaleId the value for my_resume_workexperience.scale_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setScaleId(Long scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.stu_userid
     *
     * @return the value of my_resume_workexperience.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getStuUserid() {
        return stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.stu_userid
     *
     * @param stuUserid the value for my_resume_workexperience.stu_userid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setStuUserid(Long stuUserid) {
        this.stuUserid = stuUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.industry_id
     *
     * @return the value of my_resume_workexperience.industry_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.industry_id
     *
     * @param industryId the value for my_resume_workexperience.industry_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.company_name
     *
     * @return the value of my_resume_workexperience.company_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.company_name
     *
     * @param companyName the value for my_resume_workexperience.company_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.btime
     *
     * @return the value of my_resume_workexperience.btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getBtime() {
        return btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.btime
     *
     * @param btime the value for my_resume_workexperience.btime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setBtime(Date btime) {
        this.btime = btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.etime
     *
     * @return the value of my_resume_workexperience.etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Date getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.etime
     *
     * @param etime the value for my_resume_workexperience.etime
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEtime(Date etime) {
        this.etime = etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.depname
     *
     * @return the value of my_resume_workexperience.depname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.depname
     *
     * @param depname the value for my_resume_workexperience.depname
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setDepname(String depname) {
        this.depname = depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.position_name
     *
     * @return the value of my_resume_workexperience.position_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.position_name
     *
     * @param positionName the value for my_resume_workexperience.position_name
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.work_desc
     *
     * @return the value of my_resume_workexperience.work_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getWorkDesc() {
        return workDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.work_desc
     *
     * @param workDesc the value for my_resume_workexperience.work_desc
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWorkDesc(String workDesc) {
        this.workDesc = workDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.myresume_id
     *
     * @return the value of my_resume_workexperience.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getMyresumeId() {
        return myresumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.myresume_id
     *
     * @param myresumeId the value for my_resume_workexperience.myresume_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setMyresumeId(Long myresumeId) {
        this.myresumeId = myresumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_resume_workexperience.etime_now
     *
     * @return the value of my_resume_workexperience.etime_now
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Integer getEtimeNow() {
        return etimeNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_resume_workexperience.etime_now
     *
     * @param etimeNow the value for my_resume_workexperience.etime_now
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setEtimeNow(Integer etimeNow) {
        this.etimeNow = etimeNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_resume_workexperience
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resumeWorkid=").append(resumeWorkid);
        sb.append(", scaleId=").append(scaleId);
        sb.append(", stuUserid=").append(stuUserid);
        sb.append(", industryId=").append(industryId);
        sb.append(", companyName=").append(companyName);
        sb.append(", btime=").append(btime);
        sb.append(", etime=").append(etime);
        sb.append(", depname=").append(depname);
        sb.append(", positionName=").append(positionName);
        sb.append(", workDesc=").append(workDesc);
        sb.append(", myresumeId=").append(myresumeId);
        sb.append(", etimeNow=").append(etimeNow);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}