package com.lanqiao.model.zhaopin;

import java.io.Serializable;

public class UserSearchvalue implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_user_searchvalue.user_fieldid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long userFieldid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_user_searchvalue.field_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String fieldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_user_searchvalue.filed_val
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private String filedVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xz_user_searchvalue.wrapper_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private Long wrapperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xz_user_searchvalue
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_user_searchvalue.user_fieldid
     *
     * @return the value of xz_user_searchvalue.user_fieldid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getUserFieldid() {
        return userFieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_user_searchvalue.user_fieldid
     *
     * @param userFieldid the value for xz_user_searchvalue.user_fieldid
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setUserFieldid(Long userFieldid) {
        this.userFieldid = userFieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_user_searchvalue.field_id
     *
     * @return the value of xz_user_searchvalue.field_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_user_searchvalue.field_id
     *
     * @param fieldId the value for xz_user_searchvalue.field_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setFieldId(String fieldId) {
        this.fieldId = fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_user_searchvalue.filed_val
     *
     * @return the value of xz_user_searchvalue.filed_val
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public String getFiledVal() {
        return filedVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_user_searchvalue.filed_val
     *
     * @param filedVal the value for xz_user_searchvalue.filed_val
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setFiledVal(String filedVal) {
        this.filedVal = filedVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xz_user_searchvalue.wrapper_id
     *
     * @return the value of xz_user_searchvalue.wrapper_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public Long getWrapperId() {
        return wrapperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xz_user_searchvalue.wrapper_id
     *
     * @param wrapperId the value for xz_user_searchvalue.wrapper_id
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    public void setWrapperId(Long wrapperId) {
        this.wrapperId = wrapperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xz_user_searchvalue
     *
     * @mbg.generated Tue Aug 27 14:36:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userFieldid=").append(userFieldid);
        sb.append(", fieldId=").append(fieldId);
        sb.append(", filedVal=").append(filedVal);
        sb.append(", wrapperId=").append(wrapperId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}